[package]
name = "ed25519-dalek-web"
version = "0.1.0"
authors = ["Glen De Cauwsemaecker <contact@glendc.com>"]
edition = "2018"

[dependencies]
yew = "0.6.0"
rand = "0.5.0"
tiny-bip39 = "0.6.1"
ed25519-dalek = "0.9.1"
hex = "0.3.2"
