[package]
name = "hello-ed25519-dalek"
version = "0.1.0"
authors = ["Glen De Cauwsemaecker <contact@glendc.com>"]
edition = "2018"

[dependencies]
rand = "0.5.0"
tiny-bip39 = "0.6.1"
sha2 = "0.8.0"
ed25519-dalek = "1.0.0-pre.1"
hex = "0.3.2"
